baseURL = 'https://nida1kara.github.io/'
locale = 'en-us'
title = "Nida'nın Dijital Notları"
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "muhendislik"
    name = "Mühendislik"
    url = "/muhendislik/"
    weight = 10

  [[menu.main]]
    identifier = "kitaplar"
    name = "Kitaplar"
    url = "/kitaplar/"
    weight = 20